# Non-secret configuration for the pseudo.design offline CA workflow.

PSEUDO_DESIGN_CA_DOMAIN="${PSEUDO_DESIGN_CA_DOMAIN:-pseudo.design}"
PSEUDO_DESIGN_CA_URL="${PSEUDO_DESIGN_CA_URL:-https://ca.${PSEUDO_DESIGN_CA_DOMAIN}:8443}"

PSEUDO_DESIGN_CA_ROOT_NAME="${PSEUDO_DESIGN_CA_ROOT_NAME:-Pseudo Design Root CA}"
PSEUDO_DESIGN_CA_INTERMEDIATE_NAME="${PSEUDO_DESIGN_CA_INTERMEDIATE_NAME:-Pseudo Design Intermediate CA}"
PSEUDO_DESIGN_CA_PROVISIONER_NAME="${PSEUDO_DESIGN_CA_PROVISIONER_NAME:-device-enrollment}"

PSEUDO_DESIGN_CA_KEY_TYPE="${PSEUDO_DESIGN_CA_KEY_TYPE:-EC}"
PSEUDO_DESIGN_CA_CURVE="${PSEUDO_DESIGN_CA_CURVE:-P-256}"

PSEUDO_DESIGN_DEVICE_CERT_DURATION="${PSEUDO_DESIGN_DEVICE_CERT_DURATION:-24h}"
PSEUDO_DESIGN_ENROLLMENT_TOKEN_DURATION="${PSEUDO_DESIGN_ENROLLMENT_TOKEN_DURATION:-15m}"
