{
  config,
  kaiba-dns,
  kaiba-fleet,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.kaiba.pilotAgent;
  runtime = import kaiba-fleet.inputs.nixpkgs { system = "aarch64-linux"; };
  guardPython = runtime.python3.withPackages (p: [ p.cryptography ]);
  guardConfig = pkgs.writeText "kaiba-admitted-member-guard.json" (
    builtins.toJSON {
      host = config.networking.hostName;
      trust_domain = config.services.kaiba.identity.trustDomain;
      server_address = config.services.kaiba.identity.serverAddress;
      server_port = config.services.kaiba.identity.serverPort;
      state_directory = "/var/lib/kaiba/identity/local";
      receipt_file = cfg.admittedState.receiptFile;
      join_token_file = config.services.kaiba.identity.joinTokenFile;
      not_after = "2026-10-03T02:06:35Z";
      timedatectl = "${pkgs.systemd}/bin/timedatectl";
    }
  );
in
{
  imports = [
    kaiba-fleet.nixosModules.spiffe
    kaiba-dns.nixosModules.lan-secondary
  ];
  options.kaiba.pilotAgent.enable = lib.mkEnableOption "Mako's explicitly admitted SPIRE Agent and LAN DNS secondary";
  options.kaiba.pilotAgent.activate = lib.mkEnableOption "starting Mako's admitted agent and provisioned DNS replica";

  options.kaiba.pilotAgent.admittedState = {
    enable = lib.mkEnableOption "refusing SPIRE startup unless its previously admitted cache and key remain valid";
    receiptFile = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/kaiba/identity/member-bootstrap/admitted.json";
      description = "Existing root0600 receipt binding the verified admitted node, never generated by activation.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = lib.optionals cfg.admittedState.enable [
      {
        assertion = cfg.activate && config.services.kaiba.identity.agentPackage.version == "1.15.2";
        message = "The admitted member guard requires an active profile and reviewed SPIRE 1.15.2 state format.";
      }
      {
        assertion =
          cfg.admittedState.receiptFile == "/var/lib/kaiba/identity/member-bootstrap/admitted.json";
        message = "Mako's admitted receipt must remain in its reviewed private bootstrap directory.";
      }
    ];
    systemd.services.spire-agent.wants = lib.optional cfg.admittedState.enable "systemd-time-wait-sync.service";
    systemd.services.spire-agent.after = lib.optional cfg.admittedState.enable "systemd-time-wait-sync.service";
    systemd.services.spire-agent.serviceConfig.ExecStartPre = lib.mkIf cfg.admittedState.enable [
      "+${guardPython}/bin/python3 -I -B ${./member-identity-guard.py} ${guardConfig}"
    ];
    services.kaiba.identity = {
      enable = true;
      role = "agent";
      trustDomain = "pilot.kaiba.pseudo.design";
      serverAddress = "192.168.8.214";
      agentPackage = runtime.spire.agent;
      trustBundleFile = "/var/lib/kaiba/identity/member-bootstrap/trust-bundle.pem";
      joinTokenFile = "/run/kaiba-member-admission/join-token";
    };
    # ExecStartPost keeps the simple service in startup until its Workload API
    # exists, after SPIRE has loaded the cached node and initialized its manager.
    # Its 90s readiness deadline follows the guard's 120s leaf-validity check.
    systemd.services.spire-agent.serviceConfig.ExecStartPost = lib.mkIf cfg.admittedState.enable [
      (pkgs.writeShellScript "kaiba-admitted-member-ready" ''
        while ! ${pkgs.coreutils}/bin/timeout --kill-after=1s 3s \
          ${runtime.spire.agent}/bin/spire-agent healthcheck \
          -socketPath /run/kaiba/identity/local/public/api.sock >/dev/null 2>&1; do
          ${pkgs.coreutils}/bin/sleep 0.2
        done
      '')
    ];
    # These are additional services on an existing 2 GiB application host.
    systemd.services.spire-agent.serviceConfig = {
      TimeoutStartSec = lib.mkIf cfg.admittedState.enable 90;
      TimeoutStartFailureMode = lib.mkIf cfg.admittedState.enable "kill";
      KillMode = lib.mkIf cfg.admittedState.enable "control-group";
      SendSIGKILL = lib.mkIf cfg.admittedState.enable true;
      MemoryHigh = "128M";
      MemoryMax = "256M";
      TasksMax = 128;
    };
    users.groups.kaiba-member-identity-probe = { };
    users.users.kaiba-member-identity-probe = {
      isSystemUser = true;
      group = "kaiba-member-identity-probe";
    };
    systemd.services.kaiba-member-identity-probe = {
      description = "Verify Mako's explicitly registered local workload identity";
      requires = [ "spire-agent.service" ];
      after = [ "spire-agent.service" ];
      serviceConfig = {
        Type = "oneshot";
        User = "kaiba-member-identity-probe";
        Group = "kaiba-member-identity-probe";
        ExecStart = "${kaiba-fleet.packages.aarch64-linux.spiffe-probe}/bin/kaiba-spiffe-probe fetch --socket unix:///run/kaiba/identity/local/public/api.sock --timeout 15s";
        TimeoutStartSec = "20s";
        UMask = "0077";
        NoNewPrivileges = true;
        PrivateTmp = true;
        PrivateDevices = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        CapabilityBoundingSet = "";
        RestrictAddressFamilies = [ "AF_UNIX" ];
        MemoryMax = "128M";
        TasksMax = 64;
      };
    };
    systemd.timers.kaiba-member-identity-probe = {
      wantedBy = lib.optional cfg.activate "timers.target";
      timerConfig = {
        OnBootSec = "1min";
        OnUnitInactiveSec = "5min";
        Unit = "kaiba-member-identity-probe.service";
      };
    };
    kaiba.lanSecondary = {
      enable = true;
      zone = "pilot.kaiba.pseudo.design";
      listenAddress = "192.168.8.247";
      primary.address = "192.168.8.214";
      queryAllowedPeers = [ "192.168.8.249" ];
      knotPackage = runtime.knot-dns;
      transferSecretFile = "/var/lib/kaiba/identity/member-bootstrap/dns-transfer.secret";
    };
    systemd.services.kaiba-lan-secondary.serviceConfig = {
      MemoryHigh = "128M";
      MemoryMax = "256M";
      TasksMax = 128;
    };
    systemd.services.spire-agent.wantedBy = lib.mkIf (!cfg.activate) (lib.mkForce [ ]);
    systemd.services.kaiba-lan-secondary.wantedBy = lib.mkIf (!cfg.activate) (lib.mkForce [ ]);
  };
}
